### ISSUE TITLE
0.3.0没有bdx解析器啊

### ISSUE THREAD

**Issue by Subcv** [Happy2018new/PhoenixBuilder#6]
![屏幕截图 2024-05-08 200739](https://github.com/Happy2018new/PhoenixBuilder/assets/94346255/33639040-184c-46e1-a7a2-e1c5dd7fd6d2)

**Comment by Happy2018new** [comment]
**Omega 统一导入系统** 不支持 **BDX** 文件，请使用 **BDump** 作为其替代。

**Comment by Subcv** [comment]
bdump导入一言难尽

**Comment by Happy2018new** [comment]
在导出 **BDX** 时已进行过重排处理，因此除了早期文件或第三方生成的文件外，导入 **BDX** 将按区块进行，理论上不会缺方块。

另外，**Omega 统一导入系统** 已经过时，你应该使用更好的导入器，且本存储库也不考虑继续维护该功能。
